'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("TruckDS"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class TruckDS
    Inherits Global.System.Data.DataSet
    
    Private tableVIEW_TRUCK_CHECK As VIEW_TRUCK_CHECKDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("VIEW_TRUCK_CHECK")) Is Nothing) Then
                MyBase.Tables.Add(New VIEW_TRUCK_CHECKDataTable(ds.Tables("VIEW_TRUCK_CHECK")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0"),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property VIEW_TRUCK_CHECK() As VIEW_TRUCK_CHECKDataTable
        Get
            Return Me.tableVIEW_TRUCK_CHECK
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0"),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As TruckDS = CType(MyBase.Clone,TruckDS)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXml(reader)
            If (Not (ds.Tables("VIEW_TRUCK_CHECK")) Is Nothing) Then
                MyBase.Tables.Add(New VIEW_TRUCK_CHECKDataTable(ds.Tables("VIEW_TRUCK_CHECK")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableVIEW_TRUCK_CHECK = CType(MyBase.Tables("VIEW_TRUCK_CHECK"),VIEW_TRUCK_CHECKDataTable)
        If (initTable = true) Then
            If (Not (Me.tableVIEW_TRUCK_CHECK) Is Nothing) Then
                Me.tableVIEW_TRUCK_CHECK.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Private Sub InitClass()
        Me.DataSetName = "TruckDS"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/TruckDS.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableVIEW_TRUCK_CHECK = New VIEW_TRUCK_CHECKDataTable()
        MyBase.Tables.Add(Me.tableVIEW_TRUCK_CHECK)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Private Function ShouldSerializeVIEW_TRUCK_CHECK() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As TruckDS = New TruckDS()
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Public Delegate Sub VIEW_TRUCK_CHECKRowChangeEventHandler(ByVal sender As Object, ByVal e As VIEW_TRUCK_CHECKRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class VIEW_TRUCK_CHECKDataTable
        Inherits Global.System.Data.TypedTableBase(Of VIEW_TRUCK_CHECKRow)
        
        Private columnTRUCK_NO As Global.System.Data.DataColumn
        
        Private columnCOMPANY As Global.System.Data.DataColumn
        
        Private columnNUM_DATE As Global.System.Data.DataColumn
        
        Private columnDATE1 As Global.System.Data.DataColumn
        
        Private columnDATE2 As Global.System.Data.DataColumn
        
        Private columnCAL_EXPIRE As Global.System.Data.DataColumn
        
        Private columnCOUNT_PRINT_AUTO1 As Global.System.Data.DataColumn
        
        Private columnCOUNT_PRINT_AUTO2 As Global.System.Data.DataColumn
        
        Private columnCOUNT_PRINT_AUTO3 As Global.System.Data.DataColumn
        
        Private columnDATE_PRINT1 As Global.System.Data.DataColumn
        
        Private columnDATE_PRINT2 As Global.System.Data.DataColumn
        
        Private columnDATE_PRINT3 As Global.System.Data.DataColumn
        
        Private columnCOUNT_PRINT_MANUAL1 As Global.System.Data.DataColumn
        
        Private columnCOUNT_PRINT_MANUAL2 As Global.System.Data.DataColumn
        
        Private columnCOUNT_PRINT_MANUAL3 As Global.System.Data.DataColumn
        
        Private columnACK_NAME1 As Global.System.Data.DataColumn
        
        Private columnACK_NAME2 As Global.System.Data.DataColumn
        
        Private columnACK_NAME3 As Global.System.Data.DataColumn
        
        Private columnACK1 As Global.System.Data.DataColumn
        
        Private columnACK2 As Global.System.Data.DataColumn
        
        Private columnACK3 As Global.System.Data.DataColumn
        
        Private columnCOMMENT_1 As Global.System.Data.DataColumn
        
        Private columnCOMMENT_2 As Global.System.Data.DataColumn
        
        Private columnCOMMENT_3 As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "VIEW_TRUCK_CHECK"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property TRUCK_NOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTRUCK_NO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property COMPANYColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOMPANY
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property NUM_DATEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnNUM_DATE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property DATE1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDATE1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property DATE2Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDATE2
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property CAL_EXPIREColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCAL_EXPIRE
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property COUNT_PRINT_AUTO1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOUNT_PRINT_AUTO1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property COUNT_PRINT_AUTO2Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOUNT_PRINT_AUTO2
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property COUNT_PRINT_AUTO3Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOUNT_PRINT_AUTO3
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property DATE_PRINT1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDATE_PRINT1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property DATE_PRINT2Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDATE_PRINT2
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property DATE_PRINT3Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnDATE_PRINT3
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property COUNT_PRINT_MANUAL1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOUNT_PRINT_MANUAL1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property COUNT_PRINT_MANUAL2Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOUNT_PRINT_MANUAL2
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property COUNT_PRINT_MANUAL3Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOUNT_PRINT_MANUAL3
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property ACK_NAME1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnACK_NAME1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property ACK_NAME2Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnACK_NAME2
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property ACK_NAME3Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnACK_NAME3
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property ACK1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnACK1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property ACK2Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnACK2
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property ACK3Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnACK3
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property COMMENT_1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOMMENT_1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property COMMENT_2Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOMMENT_2
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property COMMENT_3Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOMMENT_3
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0"),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As VIEW_TRUCK_CHECKRow
            Get
                Return CType(Me.Rows(index),VIEW_TRUCK_CHECKRow)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Event VIEW_TRUCK_CHECKRowChanging As VIEW_TRUCK_CHECKRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Event VIEW_TRUCK_CHECKRowChanged As VIEW_TRUCK_CHECKRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Event VIEW_TRUCK_CHECKRowDeleting As VIEW_TRUCK_CHECKRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Event VIEW_TRUCK_CHECKRowDeleted As VIEW_TRUCK_CHECKRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Overloads Sub AddVIEW_TRUCK_CHECKRow(ByVal row As VIEW_TRUCK_CHECKRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Overloads Function AddVIEW_TRUCK_CHECKRow( _
                    ByVal TRUCK_NO As String,  _
                    ByVal COMPANY As String,  _
                    ByVal NUM_DATE As Decimal,  _
                    ByVal DATE1 As Date,  _
                    ByVal DATE2 As Date,  _
                    ByVal CAL_EXPIRE As Date,  _
                    ByVal COUNT_PRINT_AUTO1 As Decimal,  _
                    ByVal COUNT_PRINT_AUTO2 As Decimal,  _
                    ByVal COUNT_PRINT_AUTO3 As Decimal,  _
                    ByVal DATE_PRINT1 As Date,  _
                    ByVal DATE_PRINT2 As Date,  _
                    ByVal DATE_PRINT3 As Date,  _
                    ByVal COUNT_PRINT_MANUAL1 As Decimal,  _
                    ByVal COUNT_PRINT_MANUAL2 As Decimal,  _
                    ByVal COUNT_PRINT_MANUAL3 As Decimal,  _
                    ByVal ACK_NAME1 As String,  _
                    ByVal ACK_NAME2 As String,  _
                    ByVal ACK_NAME3 As String,  _
                    ByVal ACK1 As String,  _
                    ByVal ACK2 As String,  _
                    ByVal ACK3 As String,  _
                    ByVal COMMENT_1 As String,  _
                    ByVal COMMENT_2 As String,  _
                    ByVal COMMENT_3 As String) As VIEW_TRUCK_CHECKRow
            Dim rowVIEW_TRUCK_CHECKRow As VIEW_TRUCK_CHECKRow = CType(Me.NewRow,VIEW_TRUCK_CHECKRow)
            Dim columnValuesArray() As Object = New Object() {TRUCK_NO, COMPANY, NUM_DATE, DATE1, DATE2, CAL_EXPIRE, COUNT_PRINT_AUTO1, COUNT_PRINT_AUTO2, COUNT_PRINT_AUTO3, DATE_PRINT1, DATE_PRINT2, DATE_PRINT3, COUNT_PRINT_MANUAL1, COUNT_PRINT_MANUAL2, COUNT_PRINT_MANUAL3, ACK_NAME1, ACK_NAME2, ACK_NAME3, ACK1, ACK2, ACK3, COMMENT_1, COMMENT_2, COMMENT_3}
            rowVIEW_TRUCK_CHECKRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowVIEW_TRUCK_CHECKRow)
            Return rowVIEW_TRUCK_CHECKRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As VIEW_TRUCK_CHECKDataTable = CType(MyBase.Clone,VIEW_TRUCK_CHECKDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New VIEW_TRUCK_CHECKDataTable()
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Friend Sub InitVars()
            Me.columnTRUCK_NO = MyBase.Columns("TRUCK_NO")
            Me.columnCOMPANY = MyBase.Columns("COMPANY")
            Me.columnNUM_DATE = MyBase.Columns("NUM_DATE")
            Me.columnDATE1 = MyBase.Columns("DATE1")
            Me.columnDATE2 = MyBase.Columns("DATE2")
            Me.columnCAL_EXPIRE = MyBase.Columns("CAL_EXPIRE")
            Me.columnCOUNT_PRINT_AUTO1 = MyBase.Columns("COUNT_PRINT_AUTO1")
            Me.columnCOUNT_PRINT_AUTO2 = MyBase.Columns("COUNT_PRINT_AUTO2")
            Me.columnCOUNT_PRINT_AUTO3 = MyBase.Columns("COUNT_PRINT_AUTO3")
            Me.columnDATE_PRINT1 = MyBase.Columns("DATE_PRINT1")
            Me.columnDATE_PRINT2 = MyBase.Columns("DATE_PRINT2")
            Me.columnDATE_PRINT3 = MyBase.Columns("DATE_PRINT3")
            Me.columnCOUNT_PRINT_MANUAL1 = MyBase.Columns("COUNT_PRINT_MANUAL1")
            Me.columnCOUNT_PRINT_MANUAL2 = MyBase.Columns("COUNT_PRINT_MANUAL2")
            Me.columnCOUNT_PRINT_MANUAL3 = MyBase.Columns("COUNT_PRINT_MANUAL3")
            Me.columnACK_NAME1 = MyBase.Columns("ACK_NAME1")
            Me.columnACK_NAME2 = MyBase.Columns("ACK_NAME2")
            Me.columnACK_NAME3 = MyBase.Columns("ACK_NAME3")
            Me.columnACK1 = MyBase.Columns("ACK1")
            Me.columnACK2 = MyBase.Columns("ACK2")
            Me.columnACK3 = MyBase.Columns("ACK3")
            Me.columnCOMMENT_1 = MyBase.Columns("COMMENT_1")
            Me.columnCOMMENT_2 = MyBase.Columns("COMMENT_2")
            Me.columnCOMMENT_3 = MyBase.Columns("COMMENT_3")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Private Sub InitClass()
            Me.columnTRUCK_NO = New Global.System.Data.DataColumn("TRUCK_NO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTRUCK_NO)
            Me.columnCOMPANY = New Global.System.Data.DataColumn("COMPANY", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOMPANY)
            Me.columnNUM_DATE = New Global.System.Data.DataColumn("NUM_DATE", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNUM_DATE)
            Me.columnDATE1 = New Global.System.Data.DataColumn("DATE1", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDATE1)
            Me.columnDATE2 = New Global.System.Data.DataColumn("DATE2", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDATE2)
            Me.columnCAL_EXPIRE = New Global.System.Data.DataColumn("CAL_EXPIRE", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCAL_EXPIRE)
            Me.columnCOUNT_PRINT_AUTO1 = New Global.System.Data.DataColumn("COUNT_PRINT_AUTO1", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOUNT_PRINT_AUTO1)
            Me.columnCOUNT_PRINT_AUTO2 = New Global.System.Data.DataColumn("COUNT_PRINT_AUTO2", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOUNT_PRINT_AUTO2)
            Me.columnCOUNT_PRINT_AUTO3 = New Global.System.Data.DataColumn("COUNT_PRINT_AUTO3", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOUNT_PRINT_AUTO3)
            Me.columnDATE_PRINT1 = New Global.System.Data.DataColumn("DATE_PRINT1", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDATE_PRINT1)
            Me.columnDATE_PRINT2 = New Global.System.Data.DataColumn("DATE_PRINT2", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDATE_PRINT2)
            Me.columnDATE_PRINT3 = New Global.System.Data.DataColumn("DATE_PRINT3", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDATE_PRINT3)
            Me.columnCOUNT_PRINT_MANUAL1 = New Global.System.Data.DataColumn("COUNT_PRINT_MANUAL1", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOUNT_PRINT_MANUAL1)
            Me.columnCOUNT_PRINT_MANUAL2 = New Global.System.Data.DataColumn("COUNT_PRINT_MANUAL2", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOUNT_PRINT_MANUAL2)
            Me.columnCOUNT_PRINT_MANUAL3 = New Global.System.Data.DataColumn("COUNT_PRINT_MANUAL3", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOUNT_PRINT_MANUAL3)
            Me.columnACK_NAME1 = New Global.System.Data.DataColumn("ACK_NAME1", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnACK_NAME1)
            Me.columnACK_NAME2 = New Global.System.Data.DataColumn("ACK_NAME2", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnACK_NAME2)
            Me.columnACK_NAME3 = New Global.System.Data.DataColumn("ACK_NAME3", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnACK_NAME3)
            Me.columnACK1 = New Global.System.Data.DataColumn("ACK1", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnACK1)
            Me.columnACK2 = New Global.System.Data.DataColumn("ACK2", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnACK2)
            Me.columnACK3 = New Global.System.Data.DataColumn("ACK3", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnACK3)
            Me.columnCOMMENT_1 = New Global.System.Data.DataColumn("COMMENT_1", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOMMENT_1)
            Me.columnCOMMENT_2 = New Global.System.Data.DataColumn("COMMENT_2", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOMMENT_2)
            Me.columnCOMMENT_3 = New Global.System.Data.DataColumn("COMMENT_3", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOMMENT_3)
            Me.columnTRUCK_NO.AllowDBNull = false
            Me.columnTRUCK_NO.MaxLength = 10
            Me.columnCOMPANY.MaxLength = 140
            Me.columnACK_NAME1.MaxLength = 75
            Me.columnACK_NAME2.MaxLength = 75
            Me.columnACK_NAME3.MaxLength = 75
            Me.columnACK1.MaxLength = 1
            Me.columnACK2.MaxLength = 1
            Me.columnACK3.MaxLength = 1
            Me.columnCOMMENT_1.MaxLength = 100
            Me.columnCOMMENT_2.MaxLength = 100
            Me.columnCOMMENT_3.MaxLength = 100
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function NewVIEW_TRUCK_CHECKRow() As VIEW_TRUCK_CHECKRow
            Return CType(Me.NewRow,VIEW_TRUCK_CHECKRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New VIEW_TRUCK_CHECKRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(VIEW_TRUCK_CHECKRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.VIEW_TRUCK_CHECKRowChangedEvent) Is Nothing) Then
                RaiseEvent VIEW_TRUCK_CHECKRowChanged(Me, New VIEW_TRUCK_CHECKRowChangeEvent(CType(e.Row,VIEW_TRUCK_CHECKRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.VIEW_TRUCK_CHECKRowChangingEvent) Is Nothing) Then
                RaiseEvent VIEW_TRUCK_CHECKRowChanging(Me, New VIEW_TRUCK_CHECKRowChangeEvent(CType(e.Row,VIEW_TRUCK_CHECKRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.VIEW_TRUCK_CHECKRowDeletedEvent) Is Nothing) Then
                RaiseEvent VIEW_TRUCK_CHECKRowDeleted(Me, New VIEW_TRUCK_CHECKRowChangeEvent(CType(e.Row,VIEW_TRUCK_CHECKRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.VIEW_TRUCK_CHECKRowDeletingEvent) Is Nothing) Then
                RaiseEvent VIEW_TRUCK_CHECKRowDeleting(Me, New VIEW_TRUCK_CHECKRowChangeEvent(CType(e.Row,VIEW_TRUCK_CHECKRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub RemoveVIEW_TRUCK_CHECKRow(ByVal row As VIEW_TRUCK_CHECKRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
            Dim ds As TruckDS = New TruckDS()
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "VIEW_TRUCK_CHECKDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    Partial Public Class VIEW_TRUCK_CHECKRow
        Inherits Global.System.Data.DataRow
        
        Private tableVIEW_TRUCK_CHECK As VIEW_TRUCK_CHECKDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableVIEW_TRUCK_CHECK = CType(Me.Table,VIEW_TRUCK_CHECKDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property TRUCK_NO() As String
            Get
                Return CType(Me(Me.tableVIEW_TRUCK_CHECK.TRUCK_NOColumn),String)
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.TRUCK_NOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property COMPANY() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.COMPANYColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'COMPANY' in table 'VIEW_TRUCK_CHECK' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.COMPANYColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property NUM_DATE() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.NUM_DATEColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'NUM_DATE' in table 'VIEW_TRUCK_CHECK' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.NUM_DATEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property DATE1() As Date
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.DATE1Column),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DATE1' in table 'VIEW_TRUCK_CHECK' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.DATE1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property DATE2() As Date
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.DATE2Column),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DATE2' in table 'VIEW_TRUCK_CHECK' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.DATE2Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property CAL_EXPIRE() As Date
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.CAL_EXPIREColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'CAL_EXPIRE' in table 'VIEW_TRUCK_CHECK' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.CAL_EXPIREColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property COUNT_PRINT_AUTO1() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_AUTO1Column),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'COUNT_PRINT_AUTO1' in table 'VIEW_TRUCK_CHECK' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_AUTO1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property COUNT_PRINT_AUTO2() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_AUTO2Column),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'COUNT_PRINT_AUTO2' in table 'VIEW_TRUCK_CHECK' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_AUTO2Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property COUNT_PRINT_AUTO3() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_AUTO3Column),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'COUNT_PRINT_AUTO3' in table 'VIEW_TRUCK_CHECK' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_AUTO3Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property DATE_PRINT1() As Date
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.DATE_PRINT1Column),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DATE_PRINT1' in table 'VIEW_TRUCK_CHECK' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.DATE_PRINT1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property DATE_PRINT2() As Date
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.DATE_PRINT2Column),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DATE_PRINT2' in table 'VIEW_TRUCK_CHECK' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.DATE_PRINT2Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property DATE_PRINT3() As Date
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.DATE_PRINT3Column),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DATE_PRINT3' in table 'VIEW_TRUCK_CHECK' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.DATE_PRINT3Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property COUNT_PRINT_MANUAL1() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_MANUAL1Column),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'COUNT_PRINT_MANUAL1' in table 'VIEW_TRUCK_CHECK' is DBNull."& _ 
                            "", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_MANUAL1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property COUNT_PRINT_MANUAL2() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_MANUAL2Column),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'COUNT_PRINT_MANUAL2' in table 'VIEW_TRUCK_CHECK' is DBNull."& _ 
                            "", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_MANUAL2Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property COUNT_PRINT_MANUAL3() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_MANUAL3Column),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'COUNT_PRINT_MANUAL3' in table 'VIEW_TRUCK_CHECK' is DBNull."& _ 
                            "", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_MANUAL3Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property ACK_NAME1() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.ACK_NAME1Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ACK_NAME1' in table 'VIEW_TRUCK_CHECK' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.ACK_NAME1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property ACK_NAME2() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.ACK_NAME2Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ACK_NAME2' in table 'VIEW_TRUCK_CHECK' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.ACK_NAME2Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property ACK_NAME3() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.ACK_NAME3Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ACK_NAME3' in table 'VIEW_TRUCK_CHECK' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.ACK_NAME3Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property ACK1() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.ACK1Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ACK1' in table 'VIEW_TRUCK_CHECK' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.ACK1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property ACK2() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.ACK2Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ACK2' in table 'VIEW_TRUCK_CHECK' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.ACK2Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property ACK3() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.ACK3Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ACK3' in table 'VIEW_TRUCK_CHECK' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.ACK3Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property COMMENT_1() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.COMMENT_1Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'COMMENT_1' in table 'VIEW_TRUCK_CHECK' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.COMMENT_1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property COMMENT_2() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.COMMENT_2Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'COMMENT_2' in table 'VIEW_TRUCK_CHECK' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.COMMENT_2Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Property COMMENT_3() As String
            Get
                Try 
                    Return CType(Me(Me.tableVIEW_TRUCK_CHECK.COMMENT_3Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'COMMENT_3' in table 'VIEW_TRUCK_CHECK' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableVIEW_TRUCK_CHECK.COMMENT_3Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsCOMPANYNull() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.COMPANYColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetCOMPANYNull()
            Me(Me.tableVIEW_TRUCK_CHECK.COMPANYColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsNUM_DATENull() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.NUM_DATEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetNUM_DATENull()
            Me(Me.tableVIEW_TRUCK_CHECK.NUM_DATEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsDATE1Null() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.DATE1Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetDATE1Null()
            Me(Me.tableVIEW_TRUCK_CHECK.DATE1Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsDATE2Null() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.DATE2Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetDATE2Null()
            Me(Me.tableVIEW_TRUCK_CHECK.DATE2Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsCAL_EXPIRENull() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.CAL_EXPIREColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetCAL_EXPIRENull()
            Me(Me.tableVIEW_TRUCK_CHECK.CAL_EXPIREColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsCOUNT_PRINT_AUTO1Null() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_AUTO1Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetCOUNT_PRINT_AUTO1Null()
            Me(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_AUTO1Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsCOUNT_PRINT_AUTO2Null() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_AUTO2Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetCOUNT_PRINT_AUTO2Null()
            Me(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_AUTO2Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsCOUNT_PRINT_AUTO3Null() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_AUTO3Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetCOUNT_PRINT_AUTO3Null()
            Me(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_AUTO3Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsDATE_PRINT1Null() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.DATE_PRINT1Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetDATE_PRINT1Null()
            Me(Me.tableVIEW_TRUCK_CHECK.DATE_PRINT1Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsDATE_PRINT2Null() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.DATE_PRINT2Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetDATE_PRINT2Null()
            Me(Me.tableVIEW_TRUCK_CHECK.DATE_PRINT2Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsDATE_PRINT3Null() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.DATE_PRINT3Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetDATE_PRINT3Null()
            Me(Me.tableVIEW_TRUCK_CHECK.DATE_PRINT3Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsCOUNT_PRINT_MANUAL1Null() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_MANUAL1Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetCOUNT_PRINT_MANUAL1Null()
            Me(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_MANUAL1Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsCOUNT_PRINT_MANUAL2Null() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_MANUAL2Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetCOUNT_PRINT_MANUAL2Null()
            Me(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_MANUAL2Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsCOUNT_PRINT_MANUAL3Null() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_MANUAL3Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetCOUNT_PRINT_MANUAL3Null()
            Me(Me.tableVIEW_TRUCK_CHECK.COUNT_PRINT_MANUAL3Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsACK_NAME1Null() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.ACK_NAME1Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetACK_NAME1Null()
            Me(Me.tableVIEW_TRUCK_CHECK.ACK_NAME1Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsACK_NAME2Null() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.ACK_NAME2Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetACK_NAME2Null()
            Me(Me.tableVIEW_TRUCK_CHECK.ACK_NAME2Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsACK_NAME3Null() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.ACK_NAME3Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetACK_NAME3Null()
            Me(Me.tableVIEW_TRUCK_CHECK.ACK_NAME3Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsACK1Null() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.ACK1Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetACK1Null()
            Me(Me.tableVIEW_TRUCK_CHECK.ACK1Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsACK2Null() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.ACK2Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetACK2Null()
            Me(Me.tableVIEW_TRUCK_CHECK.ACK2Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsACK3Null() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.ACK3Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetACK3Null()
            Me(Me.tableVIEW_TRUCK_CHECK.ACK3Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsCOMMENT_1Null() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.COMMENT_1Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetCOMMENT_1Null()
            Me(Me.tableVIEW_TRUCK_CHECK.COMMENT_1Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsCOMMENT_2Null() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.COMMENT_2Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetCOMMENT_2Null()
            Me(Me.tableVIEW_TRUCK_CHECK.COMMENT_2Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Function IsCOMMENT_3Null() As Boolean
            Return Me.IsNull(Me.tableVIEW_TRUCK_CHECK.COMMENT_3Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub SetCOMMENT_3Null()
            Me(Me.tableVIEW_TRUCK_CHECK.COMMENT_3Column) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
    Public Class VIEW_TRUCK_CHECKRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As VIEW_TRUCK_CHECKRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public Sub New(ByVal row As VIEW_TRUCK_CHECKRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Row() As VIEW_TRUCK_CHECKRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "16.0.0.0")>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
